export const browserCoreExamples = [
  "ernos browser status",
  "ernos browser start",
  "ernos browser stop",
  "ernos browser tabs",
  "ernos browser open https://example.com",
  "ernos browser focus abcd1234",
  "ernos browser close abcd1234",
  "ernos browser screenshot",
  "ernos browser screenshot --full-page",
  "ernos browser screenshot --ref 12",
  "ernos browser snapshot",
  "ernos browser snapshot --format aria --limit 200",
  "ernos browser snapshot --efficient",
  "ernos browser snapshot --labels",
];

export const browserActionExamples = [
  "ernos browser navigate https://example.com",
  "ernos browser resize 1280 720",
  "ernos browser click 12 --double",
  'ernos browser type 23 "hello" --submit',
  "ernos browser press Enter",
  "ernos browser hover 44",
  "ernos browser drag 10 11",
  "ernos browser select 9 OptionA OptionB",
  "ernos browser upload /tmp/ernos/uploads/file.pdf",
  'ernos browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "ernos browser dialog --accept",
  'ernos browser wait --text "Done"',
  "ernos browser evaluate --fn '(el) => el.textContent' --ref 7",
  "ernos browser console --level error",
  "ernos browser pdf",
];
