/**
 * ChatDev Tools Import — Bidirectional Tool Sharing
 *
 * Makes ChatDev's native tools (file ops, code exec, UV package management)
 * available to ErnOS's tool system. These execute via the ChatDev sidecar API.
 */

import { Type } from "@sinclair/typebox";
import type { AnyAgentTool } from "../agents/tools/common.js";
import { readStringParam, jsonResult, ToolInputError } from "../agents/tools/common.js";
import { createSubsystemLogger } from "../logging/subsystem.js";

const log = createSubsystemLogger("chatdev-tools-import");

interface ChatDevToolsConfig {
  /** Base URL of ChatDev sidecar */
  baseUrl: string;
}

/**
 * Create ErnOS-compatible tools that proxy to ChatDev's native tool system.
 * These give ErnOS access to ChatDev's file operations, code execution, etc.
 */
export function createChatDevImportedTools(config: ChatDevToolsConfig): AnyAgentTool[] {
  const { baseUrl } = config;

  const codeExecTool: AnyAgentTool = {
    label: "ChatDev Code Exec",
    name: "chatdev_code_exec",
    description: [
      "Execute Python code in ChatDev's sandboxed code_workspace.",
      "Useful for running scripts, data analysis, or testing code generated by workflows.",
      "Code runs in ChatDev's Python environment with access to installed packages.",
    ].join(" "),
    parameters: Type.Object({
      code: Type.String({ description: "Python code to execute." }),
      timeout: Type.Optional(Type.Number({ description: "Timeout in seconds (default: 30)." })),
    }),
    ownerOnly: true,
    execute: async (_toolCallId: string, args: Record<string, unknown>) => {
      const params = args as Record<string, unknown>;
      const code = readStringParam(params, "code", { required: true });
      const timeout = (params.timeout as number | undefined) ?? 30;

      try {
        const response = await fetch(`${baseUrl}/api/tools/python_exec`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ code, timeout }),
        });

        if (!response.ok) {
          const errorText = await response.text().catch(() => "unknown");
          return jsonResult({ success: false, error: `HTTP ${response.status}: ${errorText}` });
        }

        const result = (await response.json()) as Record<string, unknown>;
        return jsonResult({
          success: true,
          stdout: result.stdout,
          stderr: result.stderr,
          exit_code: result.exit_code,
        });
      } catch (err) {
        return jsonResult({
          success: false,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    },
  };

  const fileReadTool: AnyAgentTool = {
    label: "ChatDev File Read",
    name: "chatdev_file_read",
    description:
      "Read a file from ChatDev's code_workspace. Useful for inspecting output files from workflows.",
    parameters: Type.Object({
      path: Type.String({
        description: "File path relative to code_workspace.",
      }),
    }),
    ownerOnly: true,
    execute: async (_toolCallId: string, args: Record<string, unknown>) => {
      const params = args as Record<string, unknown>;
      const filePath = readStringParam(params, "path", { required: true });

      try {
        const response = await fetch(
          `${baseUrl}/api/tools/read_file?path=${encodeURIComponent(filePath)}`,
        );
        if (!response.ok) {
          return jsonResult({
            success: false,
            error: `HTTP ${response.status}`,
          });
        }
        const content = await response.text();
        return jsonResult({ success: true, content: content.slice(0, 8000) });
      } catch (err) {
        return jsonResult({
          success: false,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    },
  };

  const fileListTool: AnyAgentTool = {
    label: "ChatDev File List",
    name: "chatdev_file_list",
    description: "List files in ChatDev's code_workspace or WareHouse output directories.",
    parameters: Type.Object({
      path: Type.Optional(
        Type.String({
          description: "Directory path relative to code_workspace (default: root).",
        }),
      ),
    }),
    ownerOnly: true,
    execute: async (_toolCallId: string, args: Record<string, unknown>) => {
      const params = args as Record<string, unknown>;
      const dirPath = (params.path as string) ?? ".";

      try {
        const response = await fetch(
          `${baseUrl}/api/tools/list_directory?path=${encodeURIComponent(dirPath)}`,
        );
        if (!response.ok) {
          return jsonResult({
            success: false,
            error: `HTTP ${response.status}`,
          });
        }
        const result = (await response.json()) as Record<string, unknown>;
        return jsonResult({ success: true, files: result });
      } catch (err) {
        return jsonResult({
          success: false,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    },
  };

  return [codeExecTool, fileReadTool, fileListTool];
}
