#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${ERNOS_INSTALL_E2E_IMAGE:-${ERNOS_INSTALL_E2E_IMAGE:-ernos-install-e2e:local}}"
INSTALL_URL="${ERNOS_INSTALL_URL:-${ERNOS_INSTALL_URL:-https://ernos.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
ERNOS_E2E_MODELS="${ERNOS_E2E_MODELS:-${ERNOS_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e ERNOS_INSTALL_URL="$INSTALL_URL" \
  -e ERNOS_INSTALL_TAG="${ERNOS_INSTALL_TAG:-${ERNOS_INSTALL_TAG:-latest}}" \
  -e ERNOS_E2E_MODELS="$ERNOS_E2E_MODELS" \
  -e ERNOS_INSTALL_E2E_PREVIOUS="${ERNOS_INSTALL_E2E_PREVIOUS:-${ERNOS_INSTALL_E2E_PREVIOUS:-}}" \
  -e ERNOS_INSTALL_E2E_SKIP_PREVIOUS="${ERNOS_INSTALL_E2E_SKIP_PREVIOUS:-${ERNOS_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
